name: Build Python Wheels

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-wheels:
    name: Build Python Wheels (${{ matrix.OS }})

    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-24.04"]

    runs-on: ${{ matrix.OS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          show-progress: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.0
        with:
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-gs-madrona-linux
          path: wheelhouse/*.whl

  publish-pypi-manylinux:
    name: Publish on PyPi the wheel for Linux
    runs-on: ubuntu-24.04
    permissions:
      id-token: write

    needs: build-wheels
    if: github.repository == 'Genesis-Embodied-AI/gs-madrona' && github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Download the wheels previously generated
      uses: actions/download-artifact@v4
      with:
        pattern: wheelhouse-*
        merge-multiple: true
        path: wheelhouse

    - name: Publish the wheels on PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        packages-dir: wheelhouse
        verify-metadata: true
